"""empty message

Revision ID: 3610d304b4f8
Revises: 4e7f8ec5f14e
Create Date: 2024-07-30 13:55:33.228023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3610d304b4f8'
down_revision: Union[str, None] = '4e7f8ec5f14e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
